<%@ Page Language="C#" AutoEventWireup="true" CodeFile="GeneralInformation.aspx.cs" MasterPageFile="~/FinalMaster.master" Inherits="GeneralInformation" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
          
    <h2 class="section-header" style="margin: 0px; padding: 0px 0px 12.15px; border: 0px; outline: 0px; font-size: 3.6rem; vertical-align: baseline; font-family: HelveticaNeue-Light, 'Helvetica Neue Light', 'Helvetica Neue', HelvLightIBM, Arial, sans-serif; font-weight: 300; line-height: 4.86rem; color: rgb(0, 0, 0); font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Leadership in the Era of Cloud &amp; Mobile</h2>
    <p style="margin: 0px; padding: 0px 0px 7.992px; border: 0px; outline: 0px; font-size: 22px; vertical-align: baseline; color: rgb(51, 51, 51); font-family: HelveticaNeue-Light, 'Helvetica Neue Light', 'Helvetica Neue', HelvLightIBM, Arial, sans-serif; font-style: normal; font-variant: normal; font-weight: 300; letter-spacing: normal; line-height: 33px; orphans: auto; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Welcome to the brand new IBM InterConnect 2015: The Premier Cloud &amp; Mobile Conference. In today&#39;s digital economy, the impact of Cloud, Mobile, DevOps and Security on business is pervasive.<span class="Apple-converted-space">&nbsp;</span><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: inherit; vertical-align: baseline; font-family: HelveticaNeue-Bold, HelvBoldIBM, Arial, sans-serif; font-weight: 300;">Cloud</strong>, the great equalizer.<span class="Apple-converted-space">&nbsp;</span><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: inherit; vertical-align: baseline; font-family: HelveticaNeue-Bold, HelvBoldIBM, Arial, sans-serif; font-weight: 300;">Mobile</strong>, the activation point.<span class="Apple-converted-space">&nbsp;</span><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: inherit; vertical-align: baseline; font-family: HelveticaNeue-Bold, HelvBoldIBM, Arial, sans-serif; font-weight: 300;">DevOps</strong>, 
        the culmination of innovation. All underpinned by<span class="Apple-converted-space">&nbsp;</span><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: inherit; vertical-align: baseline; font-family: HelveticaNeue-Bold, HelvBoldIBM, Arial, sans-serif; font-weight: 300;">Security</strong>.</p>
    <p style="margin: 0px; padding: 0px 0px 7.992px; border: 0px; outline: 0px; font-size: 22px; vertical-align: baseline; color: rgb(51, 51, 51); font-family: HelveticaNeue-Light, 'Helvetica Neue Light', 'Helvetica Neue', HelvLightIBM, Arial, sans-serif; font-style: normal; font-variant: normal; font-weight: 300; letter-spacing: normal; line-height: 33px; orphans: auto; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        By Incorporating three dynamic IBM conferences — Impact, Innovate and Pulse — into one, InterConnect has become the most comprehensive and collaborative event ever, providing an even richer experience to you and your colleagues. Join the largest community embodying the full life-cycle of IT, assets and infrastructure — from Development to Architecture to Operations.</p>
          
</asp:Content>

